// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package department

import (
	"forest_resources_management_system_gf/api/department"
)

type ControllerDepartment_v1 struct{}

func NewDepartment_v1() department.IDepartmentDepartment_v1 {
	return &ControllerDepartment_v1{}
}
