// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tree_species

import (
	"forest_resources_management_system_gf/api/tree_species"
)

type ControllerTree_species_v1 struct{}

func NewTree_species_v1() tree_species.ITreeSpeciesTree_species_v1 {
	return &ControllerTree_species_v1{}
}
