// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"forest_resources_management_system_gf/api/user"
)

type ControllerUser_v1 struct{}

func NewUser_v1() user.IUserUser_v1 {
	return &ControllerUser_v1{}
}

type ControllerUser_v2 struct{}

func NewUser_v2() user.IUserUser_v2 {
	return &ControllerUser_v2{}
}
