// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package identity

import (
	"forest_resources_management_system_gf/api/identity"
)

type ControllerIdentity_v1 struct{}

func NewIdentity_v1() identity.IIdentityIdentity_v1 {
	return &ControllerIdentity_v1{}
}
