// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package forest

import (
	"forest_resources_management_system_gf/api/forest"
)

type ControllerForest_v1 struct{}

func NewForest_v1() forest.IForestForest_v1 {
	return &ControllerForest_v1{}
}
