// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"forest_resources_management_system_gf/api/chat"
)

type ControllerChar_v1 struct{}

func NewChar_v1() chat.IChatChar_v1 {
	return &ControllerChar_v1{}
}
