// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package department_affiche

import (
	"forest_resources_management_system_gf/api/department_affiche"
)

type ControllerDepartment_affiche_v1 struct{}

func NewDepartment_affiche_v1() department_affiche.IDepartmentAfficheDepartment_affiche_v1 {
	return &ControllerDepartment_affiche_v1{}
}
