// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package resource

import (
	"forest_resources_management_system_gf/api/resource"
)

type ControllerResource_v1 struct{}

func NewResource_v1() resource.IResourceResource_v1 {
	return &ControllerResource_v1{}
}
