// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalDepartmentAfficheDao is internal type for wrapping internal DAO implements.
type internalDepartmentAfficheDao = *internal.DepartmentAfficheDao

// departmentAfficheDao is the data access object for table department_affiche.
// You can define custom methods on it to extend its functionality as you wish.
type departmentAfficheDao struct {
	internalDepartmentAfficheDao
}

var (
	// DepartmentAffiche is globally public accessible object for table department_affiche operations.
	DepartmentAffiche = departmentAfficheDao{
		internal.NewDepartmentAfficheDao(),
	}
)

// Fill with you ideas below.
