// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalForestDao is internal type for wrapping internal DAO implements.
type internalForestDao = *internal.ForestDao

// forestDao is the data access object for table forest.
// You can define custom methods on it to extend its functionality as you wish.
type forestDao struct {
	internalForestDao
}

var (
	// Forest is globally public accessible object for table forest operations.
	Forest = forestDao{
		internal.NewForestDao(),
	}
)

// Fill with you ideas below.
