// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalForestResourceInfoDao is internal type for wrapping internal DAO implements.
type internalForestResourceInfoDao = *internal.ForestResourceInfoDao

// forestResourceInfoDao is the data access object for table forest_resource_info.
// You can define custom methods on it to extend its functionality as you wish.
type forestResourceInfoDao struct {
	internalForestResourceInfoDao
}

var (
	// ForestResourceInfo is globally public accessible object for table forest_resource_info operations.
	ForestResourceInfo = forestResourceInfoDao{
		internal.NewForestResourceInfoDao(),
	}
)

// Fill with you ideas below.
