// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalGroupChatDao is internal type for wrapping internal DAO implements.
type internalGroupChatDao = *internal.GroupChatDao

// groupChatDao is the data access object for table group_chat.
// You can define custom methods on it to extend its functionality as you wish.
type groupChatDao struct {
	internalGroupChatDao
}

var (
	// GroupChat is globally public accessible object for table group_chat operations.
	GroupChat = groupChatDao{
		internal.NewGroupChatDao(),
	}
)

// Fill with you ideas below.
