// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalModuleDao is internal type for wrapping internal DAO implements.
type internalModuleDao = *internal.ModuleDao

// moduleDao is the data access object for table module.
// You can define custom methods on it to extend its functionality as you wish.
type moduleDao struct {
	internalModuleDao
}

var (
	// Module is globally public accessible object for table module operations.
	Module = moduleDao{
		internal.NewModuleDao(),
	}
)

// Fill with you ideas below.
