// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalPeopleApplicationDao is internal type for wrapping internal DAO implements.
type internalPeopleApplicationDao = *internal.PeopleApplicationDao

// peopleApplicationDao is the data access object for table people_application.
// You can define custom methods on it to extend its functionality as you wish.
type peopleApplicationDao struct {
	internalPeopleApplicationDao
}

var (
	// PeopleApplication is globally public accessible object for table people_application operations.
	PeopleApplication = peopleApplicationDao{
		internal.NewPeopleApplicationDao(),
	}
)

// Fill with you ideas below.
