// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"forest_resources_management_system_gf/internal/dao/internal"
)

// internalPolicyDao is internal type for wrapping internal DAO implements.
type internalPolicyDao = *internal.PolicyDao

// policyDao is the data access object for table policy.
// You can define custom methods on it to extend its functionality as you wish.
type policyDao struct {
	internalPolicyDao
}

var (
	// Policy is globally public accessible object for table policy operations.
	Policy = policyDao{
		internal.NewPolicyDao(),
	}
)

// Fill with you ideas below.
