// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package module

import (
	"forest_resources_management_system_gf/api/module"
)

type ControllerModule_v1 struct{}

func NewModule_v1() module.IModuleModule_v1 {
	return &ControllerModule_v1{}
}
