// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tst

import (
	"forest_resources_management_system_gf/api/tst"
)

type ControllerTst_v1 struct{}

func NewTst_v1() tst.ITstTst_v1 {
	return &ControllerTst_v1{}
}
