// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package policy

import (
	"forest_resources_management_system_gf/api/policy"
)

type ControllerPolicy_v1 struct{}

func NewPolicy_v1() policy.IPolicyPolicy_v1 {
	return &ControllerPolicy_v1{}
}
