// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package forest_resource_info

import (
	"forest_resources_management_system_gf/api/forest_resource_info"
)

type ControllerForest_resource_info_v1 struct{}

func NewForest_resource_info_v1() forest_resource_info.IForestResourceInfoForest_resource_info_v1 {
	return &ControllerForest_resource_info_v1{}
}
