// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notice

import (
	"forest_resources_management_system_gf/api/notice"
)

type ControllerNotice_v1 struct{}

func NewNotice_v1() notice.INoticeNotice_v1 {
	return &ControllerNotice_v1{}
}
