// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package people_application

import (
	"forest_resources_management_system_gf/api/people_application"
)

type ControllerPeople_application_v1 struct{}

func NewPeople_application_v1() people_application.IPeopleApplicationPeople_application_v1 {
	return &ControllerPeople_application_v1{}
}
